#!/bin/sh

set -e
lb config noauto \
	--memtest none \
	--architectures amd64 \
	--binary-images iso-hybrid \
	--distribution testing \
	--archive-areas "main contrib non-free" \
    	--mirror-bootstrap http://ftp.de.debian.org/debian/ \
       	--mirror-chroot-security http://ftp.de.debian.org/debian-security/ \
     	--mirror-binary http://ftp.de.debian.org/debian/ \
	"${@}"



