#!/bin/sh

set -e
lb config noauto \
	--memtest none \
	--architectures i386 \
	--binary-images iso-hybrid \
	--distribution stable \
    --linux-flavours 686-pae \
	--archive-areas "main contrib non-free" \
    --mirror-bootstrap http://ftp.de.debian.org/debian/ \
    --initsystem sysvinit \
    --mirror-chroot-security http://ftp.de.debian.org/debian-security/ \
    --mirror-binary http://ftp.de.debian.org/debian/ \
	"${@}"



